mailman-elixir/mailman

lib/mailman/eex_composer.ex
test/mailman_test.exs

The template was always using the text template, this updates it to use
the proper one
Closes #4

Fixes HTML email encoding

---

lib/mailman/render.ex

Mail.app and other clients don't display the html part. According to http://stackoverflow.com/questions/5188605/gmail-displays-plain-text-email-instead-html, parts in a multipart MIME message should be in order of increasing preference. With this change mail.app (and thunderbird) shows the html mail

move html part after text part

---

lib/mailman/attachment.ex
lib/mailman/render.ex
test/attachments_test.exs

Thanks for the plugin.  Here are some updates on issues we encountered.
The mime list is obviously incomplete. I am including here the support for Apple's mobileconfig profiles, but still need some thought on how to be more flexible with the mime types. Also added the support for unknown MIME types. I think it's better to let developers attach anything and just use generic MIME type if format is unrecognised.
There was no need to have the leading dot added to the file_path, since it is being expanded, and expansion takes care of the current dir dot:
iex(1)> Path.expand("tmp") == Path.expand( Path.join(".", "tmp"))
true
All tests passing.
Cheers!
UPDATE
** sorry, I made the first PR from master, and since I have to use my master in mix for my app, all changes get here. 
I encountered a …

Apple mobileconfig MIME type, default type for unknown MIME, Path bug-fix

---

lib/mailman/external_smtp_adapter.ex

Just going to reopen this because I think it's quite crucial. I'd be quite open to making this a separate function, if you wanted to maintain backwards compatibility (deliver_blocking or something like that).
One of my main problems is that you return an {:ok } tuple no matter what happens to the email. I was using this with Amazon SES which has rate-limiting, if I sent more than 14 emails per second, it would just fail and throw away the rest - but I didn't know which had failed. So by changing this to sync, and managing the tasks myself (I have a little task library that deals with retrying on failure etc), it worked great. I've been sending about 500 emails per day for the last six weeks with this library :)

Mailman removing Async

---

lib/mailman/attachment.ex
lib/mailman/parsing.ex
lib/mailman/render.ex
test/attachments_test.exs
test/mailman_test.exs

So here is the issue, no Base64 encoding is needed since underlying gen_smtp will do it for you. Like this, you base64 encode the file twice, so the attachment isn't really valid.

removing base64 encoding and support for disposition filename

---

lib/mailman/external_smtp_adapter.ex

When sending emails, the email address in the envelope needs to be stripped from the full name. So, if the sender or reciepient is given as "Jim Jack j.j@test.com" only "j.j@test.com" should be given to the envelope. Otherwise, postfix won't send the email.

Sending emails with full name does not work

---

lib/mailman/external_smtp_adapter.ex

The current error structure returned by when using `gen_smtp_client.send_blocking` can be either `{error, Type, Message}` or `{error, Reason}` [ref](https://github.com/Vagabond/gen_smtp/blob/master/src/gen_smtp_client.erl#L96). This change will match both types of errors and return the value directly. Some examples:
```
{:error, :retries_exceeded,
{:temporary_failure, "some-relay.com", :tls_failed}}
```
```
{:error, :retries_exceeded,
{:network_failure, "some-relay.com", {:error, :timeout}}}
```

Error matching in gen_smtp_client

---

lib/mailman.ex
test/mailman_test.exs

I noticed that some external SMTP servers (Gmail, Mandrill, Sendgrid) do not handle the CC and BCC mailing. I have added a new function `deliver/3` that takes the atom `:send_cc_and_bcc` as an optional flag. This will send emails to all addresses in the CC and BCC fields in case the mail server does not take care of this. Also the BCC field is stripped and only added in to emails that have that BCC as the destination. Included are the appropriate tests.

Added deliver/3 to send CC and BCC emails

---

lib/mailman.ex
lib/mailman/parsing.ex
lib/mailman/render.ex

Prior to this commit, when compiled with Elixir 1.2, the compiler would
generate various warnings, mostly about ambiguous parameters near `|>`.
This commit adds parens to be explicit about additional parameters when
used with `|>`. This commit also adds a few other minor changes in
response to a handful of other minor compiler warnings.

update to mollify Elixir 1.2 compiler warnings

---

README.md
lib/mailman.ex
lib/mailman/context.ex
lib/mailman/local_smtp_config.ex
mix.exs

You can define from mix.config SMTP config, local SMTP or test config based on value in `config.exs`:
```elixir
config :mailman,
relay: "localhost",
port: 1025,
auth: :never
```

Allow setting configuration in Mix.Config

---

lib/mailman/context.ex

Hello,
Port wasn't being taken into account and therefore mix_local_config wasn't being used, the test suite seems to pass both before and after the changes? This should allow local config to be inferred by setting the port but not the relay.
Hope this is helpful.
Thanks,
Anthony

revised get_mix_config to account for port setting

---

README.md
lib/mailman/context.ex
test/config_test.exs

This makes it possible to set a different adapter for different environments.
This commit also includes the fix proposed in #38.
Does anyone know what the best practices are for using the application environment in tests? Is there a way to sandbox them?
It's dangerous to have to clean up what I changed in the environment in every test, and I suspect it could cause issues when running tests in parallel.

Allow explicitely setting the adapter in mix config

---

lib/mailman/test_server.ex
lib/mailman/test_server_supervisor.ex
lib/mailman/testing_adapter.ex
test/mailman_test.exs
test/test_helper.exs
test/test_server_test.exs

I found that TestServer was getting clogged with multiple messages when using async tests. This starts up a new TestServer for each calling process, so they're automatically isolated. If you're using tests that span multiple processes, you should pass the pid of the process who owns the TestServer (the one who accessed it first) to any of the TestServer functions (`deliveries`, `register_delivery`, `clear_deliveries`).
Start with Mailman.TestServerSupervisor.start_link/0. Mailman.TestServer API is nearly identical, with the exception of explicit parent process arguments (will use self() as a default).

Independent TestServer per calling process

---

README.md
lib/mailman/attachment.ex

This is a small change that highlights that the word `config` is a key of context structure.

Improving config documentation

---

lib/mailman/attachment.ex
lib/mailman/context.ex
lib/mailman/external_smtp_adapter.ex
lib/mailman/test_server.ex
test/attachments_test.exs

Hi,
I have a go at removing a few deprecations that were present in the build with latest elixir version.
The following changes were done :
- Update the mime_types count from 647 -> 648 to get the test passing (We added one at PR #60)
- Add () on the method calls
- Removed the unused variables
Most of these deprecations are present when using
```
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.3.4
```
Here is the errors that were outputted during compilation :
```
warning: variable "get_mix_config" does not exist and is being expanded to "get_mix_config()", please use parentheses to remove the ambiguity or change the variable name
lib/mailman/context.ex:9
warning: variable "mix_test_config" does not exist and is being …
```

Removed compiletime deprecations

---

.credo.exs
mix.exs
mix.lock

As per #75 I have added credo package and a basic credo configuration for static code analysis.
Currently, credo is reporting around 500 issues:
With this as starting point, we can start working towards fixing the issues reported by credo.
And for the *consistency issues* issues we might have to decide on the code format we are going to use throughout the project.

Add credo for static code analysis

---

lib/mailman.ex

Hey! I found an issue when trying to deliver a mail with BCC in my Phoenix application, it was because I have the e-mail configuration in the config files (so config as nil).  To fix that, I just changed the way we get the config. Let me know if there's anything else to be done. All the tests are passing.

Get config from Mailman.Context when using send_bcc_and_cc like in other functions

---

README.md
mix.exs
mix.lock

`eiconv` is on hex now and [mailman is using it](https://github.com/mailman-elixir/mailman/commit/5b57373326c0348dde3b12a3f9c706e6b161ad3b). So this removes the caveat at the end of the readme.

Use eiconv 1.0.0 from hex.pm

---

mix.exs
mix.lock

This commit updates the `gen_smtp` dependency to pickup some compatibility
fixes for Erlang/OPT-22, notably:
```
** (UndefinedFunctionError) function :socket.connect/5 is undefined or private
(gen_smtp) :socket.connect(:tcp, '0.0.0.0', 2525, [:binary, {:packet, :line}, {:keepalive, true}, {:active, false}], 5000)
(gen_smtp) /deps/gen_smtp/src/gen_smtp_client.erl:602: :gen_smtp_client.connect/2
(gen_smtp) /deps/gen_smtp/src/gen_smtp_client.erl:255: :gen_smtp_client.open_smtp_session/2
(gen_smtp) /deps/gen_smtp/src/gen_smtp_client.erl:200: :gen_smtp_client.try_smtp_sessions/3
(gen_smtp) /deps/gen_smtp/src/gen_smtp_client.erl:189: :gen_smtp_client.send_it/2
(mailman) lib/mailman/external_smtp_adapter.ex:17: Mailman.ExternalSmtpAdapter.deliver/3
```
Closes #85

Bump gen_smtp dependency version to 0.14.0

---

lib/mailman/smtp_config.ex

This prevents someone from accidentally logging out the config struct and exposing the password to some remote log server

Prevent password from being inspected

---

mix.exs

Updating gen_smtp from 1.0.1 to latest 1.1.1. to resolve dependency issues when using the latest version of cowboy which requires ranch 1.8.0. 
- gen_smtp 1.0.1 rebar.config: ranch 1.6.2
- gen_smtp 1.1.1 rebar.config: ranch >= 1.7.0

Updating gen_smtp from 1.0.1 to latest 1.1.1
